version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
     - "3000:8080"
    volumes:
      - ./src/:/go/src
    tty: true

    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
  
  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/config:/fluentd/etc
      - ./fluentd/log:/var/log/fluent
    restart: always
    ports:
      - "24224:24224"
  